#!/usr/bin/env perl

use Digest::MD5 qw(md5_hex);
use strict;
use warnings;

#
# keep track of open filehandles and close them
# at the end of the run for speedup when processing
# a 75GB file of messageids
#

my $filehandles = {};

while(<>) {
    chomp;
    my $line = $_;
    my ($mid, $size) = split(/ /, $line);

    my $file_id = substr(md5_hex($mid), 0, 2);
    my $filename = $file_id . '.out';

    if (! $filehandles->{$file_id}) {
        open($filehandles->{$file_id}, '>>', $filename) || die "Could not create $filename - $!\n";
    }

    my $fh = $filehandles->{$file_id};

    print $fh $line, "\n";
}

for my $filehandle (keys(%$filehandles)) {
    close($filehandles->{$filehandle});
}
